# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTextSummarizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentance',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
