# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTextSummarizer', '0002_sentance_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentance',
            name='order',
            field=models.IntegerField(blank=True),
        ),
    ]
