# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTextSummarizer', '0004_auto_20160302_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
