# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTextSummarizer', '0005_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=1000, upload_to='files/toread.txt'),
        ),
    ]
