# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTextSummarizer', '0006_auto_20160302_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=500)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
